# Generated by Django 5.2.1 on 2025-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_moodcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=50)),
                ('apply_link', models.URLField()),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
